Rename LOCATION_CODE variable to LOCATION_CODE_IN_FILENAME for clarity in deployment scripts

diff --git a/deploy/pipelines/10-remover-terraform.yaml b/deploy/pipelines/10-remover-terraform.yaml
--- a/deploy/pipelines/10-remover-terraform.yaml
+++ b/deploy/pipelines/10-remover-terraform.yaml
@@ -193,8 +193,8 @@ stages:
 
               ENVIRONMENT_IN_FILENAME=$(echo $(sap_system_folder) | awk -F'-' '{print $1}')
 
-              LOCATION_CODE=$(echo $(sap_system_folder) | awk -F'-' '{print $2}')
-              LOCATION_IN_FILENAME=$(get_region_from_code "$LOCATION_CODE" || true)
+              LOCATION_CODE_IN_FILENAME=$(echo $(sap_system_folder) | awk -F'-' '{print $2}')
+              LOCATION_IN_FILENAME=$(get_region_from_code "$LOCATION_CODE_IN_FILENAME" || true)
 
               NETWORK_IN_FILENAME=$(echo $(sap_system_folder) | awk -F'-' '{print $3}')
 
@@ -241,7 +241,7 @@ stages:
                 exit 2
               fi
 
-              workload_environment_file_name="$CONFIG_REPO_PATH/.sap_deployment_automation/${ENVIRONMENT}${LOCATION_CODE}${NETWORK}"
+              workload_environment_file_name="$CONFIG_REPO_PATH/.sap_deployment_automation/${ENVIRONMENT}${LOCATION_CODE_IN_FILENAME}${NETWORK}"
               echo "Workload Zone Environment File:      $workload_environment_file_name"
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
@@ -267,7 +267,7 @@ stages:
 
               dos2unix -q "${workload_environment_file_name}"
 
-              prefix="${ENVIRONMENT}${LOCATION_CODE}${NETWORK}"
+              prefix="${ENVIRONMENT}${LOCATION_CODE_IN_FILENAME}${NETWORK}"
 
               deployer_tfstate_key=$(getVariableFromVariableGroup "${VARIABLE_GROUP_ID}" "Deployer_State_FileName" "${workload_environment_file_name}" "deployer_tfstate_key" || true)
               export deployer_tfstate_key
@@ -444,10 +444,12 @@ stages:
               mkdir -p .sap_deployment_automation
               git checkout -q "$(Build.SourceBranchName)"
 
-              if [ ! -f "$CONFIG_REPO_PATH/SYSTEM/$(sap_system_folder)/$(sap_system_configuration)" ]; then
+              if [ ! -f "tfvarsFile" ]; then
                 echo -e "$boldred--- $(sap_system_configuration) was not found ---$reset"
-                echo "##vso[task.logissue type=error]File $(sap_system_configuration) was not found."
+                echo "##vso[task.logissue type=error]File $tfvarsFile was not found."
                 exit 2
+              else
+                dos2unix -q tfvarsFile
               fi
 
               echo -e "$green--- Validations ---$reset"
@@ -529,7 +531,6 @@ stages:
               az account set --subscription "$ARM_SUBSCRIPTION_ID"
 
               echo -e "$green--- Read deployment details ---$reset"
-              dos2unix -q tfvarsFile
 
               ENVIRONMENT=$(grep -m1 "^environment" "$tfvarsFile" | awk -F'=' '{print $2}' | tr -d ' \t\n\r\f"')
               LOCATION=$(grep -m1 "^location" "$tfvarsFile" | awk -F'=' '{print $2}' | tr '[:upper:]' '[:lower:]' | tr -d ' \t\n\r\f"')
@@ -542,8 +543,8 @@ stages:
 
               # shellcheck disable=SC2046
               # shellcheck disable=SC2005
-              LOCATION_CODE=$(echo $(sap_system_folder) | awk -F'-' '{print $2}')
-              LOCATION_IN_FILENAME=$(get_region_from_code "$LOCATION_CODE" || true)
+              LOCATION_CODE_IN_FILENAME=$(echo $(sap_system_folder) | awk -F'-' '{print $2}')
+              LOCATION_IN_FILENAME=$(get_region_from_code "$LOCATION_CODE_IN_FILENAME" || true)
 
               # shellcheck disable=SC2046
               # shellcheck disable=SC2005
@@ -594,7 +595,7 @@ stages:
                 exit 2
               fi
 
-              workload_environment_file_name="$CONFIG_REPO_PATH/.sap_deployment_automation/${ENVIRONMENT}${LOCATION_CODE}${NETWORK}"
+              workload_environment_file_name="$CONFIG_REPO_PATH/.sap_deployment_automation/${ENVIRONMENT}${LOCATION_CODE_IN_FILENAME}${NETWORK}"
               echo "Workload Zone Environment File:      $workload_environment_file_name"
 
               echo -e "$green--- Configure devops CLI extension ---$reset"
@@ -621,7 +622,7 @@ stages:
 
               dos2unix -q "${workload_environment_file_name}"
 
-              prefix="${ENVIRONMENT}${LOCATION_CODE}${NETWORK}"
+              prefix="${ENVIRONMENT}${LOCATION_CODE_IN_FILENAME}${NETWORK}"
 
               deployer_tfstate_key=$(getVariableFromVariableGroup "${VARIABLE_GROUP_ID}" "Deployer_State_FileName" "${workload_environment_file_name}" "deployer_tfstate_key" || true)
               export deployer_tfstate_key
